# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.0
    hooks: 
    # any R project
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]    
    -   id: lintr
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    #  R package development
    # -   id: roxygenize
    # -   id: use-tidy-description
    # -   id: deps-in-desc
    # -   id: codemeta-description-updated
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks: 
    -   id: check-added-large-files
        args: ['--maxkb=200']
