bm_aggregated <- mergeBenchmarkResults(list(

  bm_vi_task_svm_no_filter_mbo,
  bm_nri_task_svm_no_filter_mbo,
  bm_hr_task_svm_no_filter_mbo,
  bm_hr_vi_task_svm_no_filter_mbo,
  bm_hr_nri_task_svm_no_filter_mbo,
  bm_hr_nri_vi_task_svm_no_filter_mbo,

  bm_vi_task_svm_pca_mbo,
  bm_nri_task_svm_pca_mbo,
  bm_hr_task_svm_pca_mbo,
  bm_hr_vi_task_svm_pca_mbo,
  bm_hr_nri_task_svm_pca_mbo,
  bm_hr_nri_vi_task_svm_pca_mbo,

  bm_vi_task_svm_borda_mbo,
  bm_nri_task_svm_borda_mbo,
  bm_hr_task_svm_borda_mbo,
  bm_hr_vi_task_svm_borda_mbo,
  bm_hr_nri_task_svm_borda_mbo,
  bm_hr_nri_vi_task_svm_borda_mbo,

  bm_vi_task_svm_relief_mbo,
  bm_nri_task_svm_relief_mbo,
  bm_hr_task_svm_relief_mbo,
  bm_hr_vi_task_svm_relief_mbo,
  bm_hr_nri_task_svm_relief_mbo,
  bm_hr_nri_vi_task_svm_relief_mbo,

  bm_vi_task_svm_linear.cor_mbo,
  bm_nri_task_svm_linear.cor_mbo,
  bm_hr_task_svm_linear.cor_mbo,
  bm_hr_vi_task_svm_linear.cor_mbo,
  bm_hr_nri_task_svm_linear.cor_mbo,
  bm_hr_nri_vi_task_svm_linear.cor_mbo,

  bm_vi_task_svm_info.gain_mbo,
  bm_nri_task_svm_info.gain_mbo,
  bm_hr_task_svm_info.gain_mbo,
  bm_hr_vi_task_svm_info.gain_mbo,
  bm_hr_nri_task_svm_info.gain_mbo,
  bm_hr_nri_vi_task_svm_info.gain_mbo,

  bm_vi_task_svm_mrmr_mbo,
  bm_nri_task_svm_mrmr_mbo,
  bm_hr_task_svm_mrmr_mbo,
  bm_hr_vi_task_svm_mrmr_mbo,
  bm_hr_nri_task_svm_mrmr_mbo,
  bm_hr_nri_vi_task_svm_mrmr_mbo,

  bm_vi_task_svm_carscore_mbo,
  bm_nri_task_svm_carscore_mbo,
  bm_hr_task_svm_carscore_mbo,
  bm_hr_vi_task_svm_carscore_mbo,
  bm_hr_nri_task_svm_carscore_mbo,
  bm_hr_nri_vi_task_svm_carscore_mbo,

  bm_vi_task_svm_cmim_mbo,
  bm_nri_task_svm_cmim_mbo,
  bm_hr_task_svm_cmim_mbo,
  bm_hr_vi_task_svm_cmim_mbo,
  bm_hr_nri_task_svm_cmim_mbo,
  bm_hr_nri_vi_task_svm_cmim_mbo,

  # rf -------------------------------------------------------------------------

  bm_vi_task_rf_no_filter_mbo,
  bm_nri_task_rf_no_filter_mbo,
  bm_hr_task_rf_no_filter_mbo,
  bm_hr_vi_task_rf_no_filter_mbo,
  bm_hr_nri_task_rf_no_filter_mbo,
  bm_hr_nri_vi_task_rf_no_filter_mbo,

  bm_vi_task_rf_pca_mbo,
  bm_nri_task_rf_pca_mbo,
  bm_hr_task_rf_pca_mbo,
  bm_hr_vi_task_rf_pca_mbo,
  bm_hr_nri_task_rf_pca_mbo,
  bm_hr_nri_vi_task_rf_pca_mbo,

  bm_vi_task_rf_borda_mbo,
  bm_nri_task_rf_borda_mbo,
  bm_hr_task_rf_borda_mbo,
  bm_hr_vi_task_rf_borda_mbo,
  bm_hr_nri_task_rf_borda_mbo,
  bm_hr_nri_vi_task_rf_borda_mbo,

  bm_vi_task_rf_relief_mbo,
  bm_nri_task_rf_relief_mbo,
  bm_hr_task_rf_relief_mbo,
  bm_hr_vi_task_rf_relief_mbo,
  bm_hr_nri_task_rf_relief_mbo,
  bm_hr_nri_vi_task_rf_relief_mbo,

  bm_vi_task_rf_linear.cor_mbo,
  bm_nri_task_rf_linear.cor_mbo,
  bm_hr_task_rf_linear.cor_mbo,
  bm_hr_vi_task_rf_linear.cor_mbo,
  bm_hr_nri_task_rf_linear.cor_mbo,
  bm_hr_nri_vi_task_rf_linear.cor_mbo,

  bm_vi_task_rf_info.gain_mbo,
  bm_nri_task_rf_info.gain_mbo,
  bm_hr_task_rf_info.gain_mbo,
  bm_hr_vi_task_rf_info.gain_mbo,
  bm_hr_nri_task_rf_info.gain_mbo,
  bm_hr_nri_vi_task_rf_info.gain_mbo,

  bm_vi_task_rf_mrmr_mbo,
  bm_nri_task_rf_mrmr_mbo,
  bm_hr_task_rf_mrmr_mbo,
  bm_hr_vi_task_rf_mrmr_mbo,
  bm_hr_nri_task_rf_mrmr_mbo,
  bm_hr_nri_vi_task_rf_mrmr_mbo,

  bm_vi_task_rf_carscore_mbo,
  bm_nri_task_rf_carscore_mbo,
  bm_hr_task_rf_carscore_mbo,
  bm_hr_vi_task_rf_carscore_mbo,
  bm_hr_nri_task_rf_carscore_mbo,
  bm_hr_nri_vi_task_rf_carscore_mbo,

  bm_vi_task_rf_cmim_mbo,
  bm_nri_task_rf_cmim_mbo,
  bm_hr_task_rf_cmim_mbo,
  bm_hr_vi_task_rf_cmim_mbo,
  bm_hr_nri_task_rf_cmim_mbo,
  bm_hr_nri_vi_task_rf_cmim_mbo,

  # xgboost --------------------------------------------------------------------

  bm_vi_task_xgboost_no_filter_mbo,
  bm_nri_task_xgboost_no_filter_mbo,
  bm_hr_task_xgboost_no_filter_mbo,
  bm_hr_vi_task_xgboost_no_filter_mbo,
  bm_hr_nri_task_xgboost_no_filter_mbo,
  bm_hr_nri_vi_task_xgboost_no_filter_mbo,

  bm_vi_task_xgboost_pca_mbo,
  bm_nri_task_xgboost_pca_mbo,
  bm_hr_task_xgboost_pca_mbo,
  bm_hr_vi_task_xgboost_pca_mbo,
  bm_hr_nri_task_xgboost_pca_mbo,
  bm_hr_nri_vi_task_xgboost_pca_mbo,

  bm_vi_task_xgboost_borda_mbo,
  bm_nri_task_xgboost_borda_mbo,
  bm_hr_task_xgboost_borda_mbo,
  bm_hr_vi_task_xgboost_borda_mbo,
  bm_hr_nri_task_xgboost_borda_mbo,
  bm_hr_nri_vi_task_xgboost_borda_mbo,

  bm_vi_task_xgboost_relief_mbo,
  bm_nri_task_xgboost_relief_mbo,
  bm_hr_task_xgboost_relief_mbo,
  bm_hr_vi_task_xgboost_relief_mbo,
  bm_hr_nri_task_xgboost_relief_mbo,
  bm_hr_nri_vi_task_xgboost_relief_mbo,

  bm_vi_task_xgboost_linear.cor_mbo,
  bm_nri_task_xgboost_linear.cor_mbo,
  bm_hr_task_xgboost_linear.cor_mbo,
  bm_hr_vi_task_xgboost_linear.cor_mbo,
  bm_hr_nri_task_xgboost_linear.cor_mbo,
  bm_hr_nri_vi_task_xgboost_linear.cor_mbo,

  bm_vi_task_xgboost_info.gain_mbo,
  bm_nri_task_xgboost_info.gain_mbo,
  bm_hr_task_xgboost_info.gain_mbo,
  bm_hr_vi_task_xgboost_info.gain_mbo,
  bm_hr_nri_task_xgboost_info.gain_mbo,
  bm_hr_nri_vi_task_xgboost_info.gain_mbo,

  bm_vi_task_xgboost_mrmr_mbo,
  bm_nri_task_xgboost_mrmr_mbo,
  bm_hr_task_xgboost_mrmr_mbo,
  bm_hr_vi_task_xgboost_mrmr_mbo,
  bm_hr_nri_task_xgboost_mrmr_mbo,
  bm_hr_nri_vi_task_xgboost_mrmr_mbo,

  bm_vi_task_xgboost_carscore_mbo,
  bm_nri_task_xgboost_carscore_mbo,
  bm_hr_task_xgboost_carscore_mbo,
  bm_hr_vi_task_xgboost_carscore_mbo,
  bm_hr_nri_task_xgboost_carscore_mbo,
  bm_hr_nri_vi_task_xgboost_carscore_mbo,

  bm_vi_task_xgboost_cmim_mbo,
  bm_nri_task_xgboost_cmim_mbo,
  bm_hr_task_xgboost_cmim_mbo,
  bm_hr_vi_task_xgboost_cmim_mbo,
  bm_hr_nri_task_xgboost_cmim_mbo,
  bm_hr_nri_vi_task_xgboost_cmim_mbo,

  # lasso ----------------------------------------------------------------------

  bm_vi_task_lasso_no_filter_mbo,
  bm_nri_task_lasso_no_filter_mbo,
  bm_hr_task_lasso_no_filter_mbo,
  bm_hr_vi_task_lasso_no_filter_mbo,
  bm_hr_nri_task_lasso_no_filter_mbo,
  bm_hr_nri_vi_task_lasso_no_filter_mbo,

  bm_vi_task_lrn_lassocv,
  bm_nri_task_lrn_lassocv,
  bm_hr_task_lrn_lassocv,
  bm_hr_vi_task_lrn_lassocv,
  bm_hr_nri_task_lrn_lassocv,
  bm_hr_nri_vi_task_lrn_lassocv,

  # ridge ----------------------------------------------------------------------

  bm_vi_task_ridge_no_filter_mbo,
  bm_nri_task_ridge_no_filter_mbo,
  bm_hr_task_ridge_no_filter_mbo,
  bm_hr_vi_task_ridge_no_filter_mbo,
  bm_hr_nri_task_ridge_no_filter_mbo,
  bm_hr_nri_vi_task_ridge_no_filter_mbo,

  bm_vi_task_lrn_ridgecv,
  bm_nri_task_lrn_ridgecv,
  bm_hr_task_lrn_ridgecv,
  bm_hr_vi_task_lrn_ridgecv,
  bm_hr_nri_task_lrn_ridgecv,
  bm_hr_nri_vi_task_lrn_ridgecv
))
