file_move(
  "docs/figure/filter-correlation.Rmd/correlation-nbins-1.pdf",
  "code/98-paper/ieee/pdf"
)
file_move(
  "docs/figure/filter-correlation.Rmd/correlation-filter-nri-1.pdf",
  "code/98-paper/ieee/pdf"
)
file_move(
  "docs/figure/eda.Rmd/defoliation-distribution-plot-1.pdf",
  "code/98-paper/ieee/pdf"
)
file_move(
  here("docs/figure/spectral-signatures.Rmd/spectral-signatures-1.pdf"),
  here("code/98-paper/ieee/pdf")
)
file_move(
  here("docs/figure/eval-performance.Rmd/performance-results-1.pdf"),
  here("code/98-paper/ieee/pdf")
)
file_move(
  here("docs/figure/eval-performance.Rmd/filter-effect-1.pdf"),
  here("code/98-paper/ieee/pdf")
)
