---
title: "Create NDVI raster files for each plot"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```

```{r, results='hide'}
library(raster)
devtools::install_github("pat-s/hsdar")
library(hsdar)
library(pbmcapply)
library(glue)
library(magrittr)
library(purrr)
```

# Specify wavelength 

```{r}
wavelength = readRDS("/data/patrick/mod/hyperspectral/wavelength.Rds")
```

# Read rasters (cropped by plot) 

## list files

```{r}
list.files("/data/patrick/mod/hyperspectral/atm-cropped", 
                    pattern = ".tif$", full.names = TRUE) %>% 
  map(~ brick(.x)) -> spectral_data
```

# Coerce to class "HyperSpecRaster"

```{r}
hyperspecs = map(spectral_data, function(x) HyperSpecRaster(x, wavelength))
```

# Calculate NDVI in parallel

* Assign to `tmp` to prevent list printing to console
* Use 'NDVI2' as formula 

```{r, cache=FALSE}
tmp <- pbmclapply(hyperspecs, function(x) 
  vegindex(x, "NDVI2", 
           filename = glue("/data/patrick/mod/hyperspectral/ndvi/ndvi2-{name}",
                           name = basename(x@file@name)),
           bnames = "NDVI"), mc.cores = 28)
rm(tmp)
```


