---
title: "Calculate all possible vegetation indices that the `hsdar` package offers."
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)
```

# Load packages

```{r}
library(raster)
library(hsdar)
library(pbmcapply)
library(magrittr)
library(purrr)
library(glue)
```

# Specify wavelength

```{r}
wavelength <- readRDS("/data/patrick/mod/hyperspectral/wavelength.Rds")
```

## list files

```{r}
list.files("/data/patrick/mod/hyperspectral/atm-cropped", 
                    pattern = ".tif$", full.names = TRUE) %>% 
  map(~ brick(.x)) -> spectral_data
```

# Coerce to class "HyperSpecRaster"

```{r}
hyperspecs = map(spectral_data, function(x) HyperSpecRaster(x, wavelength))
```

# Specify indices

```{r}
# specify which indices to calculate WITH DERIVATION INDICES
indices <- c("Boochs", "Boochs2","CARI", "Carter", "Carter2", "Carter3", "Carter4", "Carter5",
             "Carter6", "CI", "CI2", "ClAInt", "CRI1", "CRI2", "CRI3", "CRI4",
             "D1", "D2",
             "Datt", "Datt2", "Datt3", "Datt4", "Datt5", "Datt6", "DD", "DDn", "DPI", "DWSI4",
             "EGFR", "EVI", "GDVI_2", "GDVI_3", "GDVI_4", "GI", "Gitelson",
             "Gitelson2", "GMI1", "GMI2", "Green NDVI", "Maccioni", "MCARI",
             "MCARI2", "mND705", "mNDVI", "MPRI", "MSAVI", "mSR",
             "mSR2", "mSR705", "MTCI", "MTVI", "NDVI", "NDVI2", "NDVI3",
             "NPCI", "OSAVI", "PARS", "PRI", "PRI_norm", "PRI*CI2", "PSRI",
             "PSSR", "PSND","SPVI", "PWI", "RDVI", "REP_Li", "SAVI", "SIPI",
             "SPVI","SR", "SR1", "SR2", "SR3", "SR4", "SR5", "SR6", "SR7",
             "SR8", "Sum_Dr1", "Sum_Dr2", "SRPI", "TCARI", "TCARI2", "TGI", "TVI", "Vogelmann",
             "Vogelmann2", "Vogelmann3", "Vogelmann4")
# length(indices)
```

# Calculate vegetation indices

Writing files as `.gri` files because this format preserves layer names. TIFF format does not!!
Layer names are changed using the `bnames` argument of function `rasterFunctions::hsdar.vegIndex()`.

```{r, cache=FALSE}
tmp <- pbmclapply(hyperspecs, function(x) 
  vegindex(x, indices, 
           filename = 
             str_replace(glue("/data/patrick/mod/hyperspectral/all-veg-indices/{name}",
                              name = basename(x@file@name)), ".tif", ".grd"), 
           na.rm = TRUE, bnames = indices), mc.cores = 28)
```


