---
title: "Extract indices to points"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r, results='hide'}
library(raster)
devtools::install_github("pat-s/hsdar")
library(hsdar)
library(pbmcapply)
library(glue)
library(magrittr)
library(sf)
library(purrr)
library(dplyr)
```

The points to which the indices are extracted to are cleaned in the file "02_preprocessing.Rmd".

# Create function

See step-by-step example for Laukiz 1 below.

```{r}
extract_to_plot = function(plot_name, buffer, cores, bf_name) {
  points = st_read(glue("/data/patrick/mod/tree-per-tree/2016/{plot_name}/{plot_name}.gpkg"),
          quiet = TRUE)
  
  ras_veg_indices <- brick(glue("/data/patrick/mod/hyperspectral/all-veg-indices/{plot_name}.grd"))
  
  ras_nbi <- brick(glue("/data/patrick/mod/hyperspectral/narrow-band-indices/narrow-band-indices-{plot_name}.grd"))
  
  # calculate buffered veg index
  out_veg <- pbmclapply(buffer, function(x) 
    raster::extract(ras_veg_indices, points, buffer = x, 
                    fun = mean, df = TRUE,
                    na.rm = TRUE), mc.cores = cores)
  
  out_veg %<>% 
    map2(seq_along(buffer), ~ setNames(.x, glue("bf{buffer}_{name}", 
                                             name = names(out_veg[[.y]]))))
  
  out_nbi <- pbmclapply(buffer, function(x)
    raster::extract(ras_nbi, points, buffer = x,
                    fun = mean, df = TRUE,
                    na.rm = TRUE) , mc.cores = cores)

  out_nbi %<>%
    map2(seq_along(buffer), ~ setNames(.x, glue("bf", .y, "_{name}",
                                             name = names(out_nbi[[.y]]))))

  # merge all data frames (buffers)
  all_veg <- bind_cols(out_veg)
  
  all_nbi <- bind_cols(out_nbi)
  
  points %<>% 
    bind_cols(all_veg) %>% 
    bind_cols(all_nbi)
  
  # .rda file (data frame)
  points %>% 
    saveRDS(glue("/data/patrick/mod/tree-per-tree/2016/{plot_name}/all-indices-{plot_name}_{bf_name}.rda"))
}
```

# Process

## Buffer: 2

```{r}
pbmclapply(c("laukiz1", "laukiz2", "oiartzun", "luiando"), 
           function(x) extract_to_plot(x, 2, cores = 1, "bf2"), 
           mc.cores = 4)
```

<!-- ## Buffer: 1 - 10 -->

<!-- ```{r} -->
<!-- pbmclapply(c("laukiz1", "laukiz2", "oiartzun", "luiando"),  -->
<!--            function(x) extract_to_plot(x, seq(1:10), cores = 10, "bf1-10"),  -->
<!--            mc.cores = 4) -->
<!-- ``` -->

<!-- ## Buffer: 1,5,10,15,20 -->

<!-- ```{r} -->
<!-- pbmclapply(c("laukiz1", "laukiz2", "oiartzun", "luiando"),  -->
<!--            function(x) extract_to_plot(x, c(1, 5, 10, 15, 20), cores = 5, "bf1-5-10-15-20"),  -->
<!--            mc.cores = 4) -->
<!-- ``` -->

<!-- ## Buffer: 1, 10, 20, 30, 40, 50 -->

<!-- ```{r} -->
<!-- pbmclapply(c("laukiz1", "laukiz2", "oiartzun", "luiando"),  -->
<!--            function(x) extract_to_plot(x, c(1, 10, 20, 30, 40, 50), cores = 6,  -->
<!--                                        "bf1-10-20-30-40-50"),  -->
<!--            mc.cores = 2) # due to RAM consumption -->
<!-- ``` -->
