---
title: "02-preprocessing"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Load packages

```{r}
library(purrr)
library(here)
library(tibble)
library(raster)
library(glue)
library(sf)
library(dplyr)
library(magrittr)
```

<!-- # Read data -->

<!-- Reading in data from .txt files and exporting them as a Geopackage (.gpkg). -->

<!-- ## Survey data -->

<!-- ```{r} -->
<!-- names <- c("laukiz1", "laukiz2", "luiando", "oiartzun") -->

<!-- map( -->
<!--   names, -->
<!--   ~ as_tibble(readr::read_csv( -->
<!--     file = glue("/data/patrick/mod/survey_data/2016/{.x}.csv" -->
<!--                 ), -->
<!--   )) -->
<!-- ) %>% -->
<!--   set_names(names) %>% -->
<!--   map(~ rename_all(.x, tolower)) -> data_tbl -->
<!-- ``` -->

<!-- ## Clean Laukiz 1 & Oiartzun coords -->

<!-- ```{r} -->
<!-- data_tbl$laukiz1 %<>% -->
<!--   select(-x, -y) %>%  -->
<!--   rename(x = lon, y = punto) -->

<!-- data_tbl$oiartzun %<>% -->
<!--   select(-x, -y) %>%  -->
<!--   rename(x = lon, y = punto) -->
<!-- ``` -->

<!-- Laukiz2 has no coordinate info in the txt file. We need to read the shapefile and join them. -->

<!-- ### Join Laukiz2 coords -->

<!-- ```{r} -->
<!-- laukiz2_coords <- st_read("/data/patrick/raw/survey_data/2016/laukiz2/arboles/Laukiz2_arboles_ETRS89.shp") -->

<!-- data_tbl$laukiz2 <- left_join(data_tbl$laukiz2, laukiz2_coords, -->
<!--   by = c("num arbol" = "id_arbol") -->
<!-- ) -->
<!-- ``` -->

<!-- Drop observations with no coordinate information. -->

<!-- ```{r} -->
<!-- data_tbl %<>% -->
<!--   map(~ drop_na(.x, c("x", "y"))) -->
<!-- ``` -->

<!-- Coerce to `sf` objects. -->

<!-- ```{r} -->
<!-- map(data_tbl, ~ st_as_sf(.x, coords = c("x", "y"))) -> data_sf -->
<!-- ``` -->

<!-- Select variables related to defoliation. -->

<!-- ```{r} -->
<!-- data_sf %<>% -->
<!--   map(~ dplyr::select(.x, contains("def"))) -->
<!-- ``` -->

<!-- Laukiz2 needs some clean up: -->

<!-- "no" -> 0 -->
<!-- "*" -> NA -->
<!-- Coerce from chr to int. -->
<!-- Calculate "deftot" which is the mean of all three parts (bottom, mid, top). -->

<!-- `rowSums` will thrown an error due to the "geometry" column so we need to add `drop = TRUE`. -->

<!-- ```{r} -->
<!-- data_sf$laukiz2 %<>% -->
<!--   mutate( -->
<!--     `% de defoliacion parte media` = -->
<!--       replace( -->
<!--         .$`% de defoliacion parte media`, -->
<!--         .$`% de defoliacion parte media` == "no", "0" -->
<!--       ) -->
<!--   ) %>% -->
<!--   mutate( -->
<!--     `% defoliacion en punta` = -->
<!--       replace( -->
<!--         .$`% defoliacion en punta`, -->
<!--         .$`% defoliacion en punta` == "no", "0" -->
<!--       ) -->
<!--   ) %>% -->
<!--   mutate( -->
<!--     `% defoliacion base` = -->
<!--       replace( -->
<!--         .$`% defoliacion base`, -->
<!--         .$`% defoliacion base` == "no", "0" -->
<!--       ) -->
<!--   ) %>% -->
<!--   mutate( -->
<!--     `% defoliacion base` = -->
<!--       replace( -->
<!--         `% defoliacion base`, -->
<!--         `% defoliacion base` == "*", NA -->
<!--       ) -->
<!--   ) %>% -->
<!--   mutate_if(is.character, as.numeric) %>% -->
<!--   mutate(deftot = as.integer(rowMeans(.[, 1:3, drop = TRUE], na.rm = TRUE))) %>% -->
<!--   drop_na(deftot) %>% -->
<!--   dplyr::select(deftot, geometry) -->
<!-- ``` -->

<!-- # Write clean data as .gpkg -->

<!-- The error messages can be ignored, writing works: https://github.com/r-spatial/sf/issues/628#issuecomment-383363473 -->

<!-- ```{r} -->
<!-- walk2(data_sf, seq_along(data_sf), ~ st_write(.x, glue("/data/patrick/mod/tree-per-tree/2016/{name}/{name}.gpkg", -->
<!--   name = names(data_sf[.y])), delete_dsn = TRUE)) -->
<!-- ``` -->

# New cleaned data From Eugenia June 2018

```{r}
data_tbl = map(c("laukiz1", "laukiz2", "luiando", "oiartzun", "hernani"), 
               ~ readr::read_csv2(glue("/data/patrick/raw/survey_data/2016/{.x}/{.x}.csv")) %>% 
                 #na.omit() %>% 
                 rename_all(tolower) %>% 
                 rename(height = heigth) %>% 
               filter_all(any_vars(!is.na(.)))) %>% 
  set_names(c("laukiz1", "laukiz2", "luiando", "oiartzun", "hernani"))

data_tbl$laukiz2 %<>% 
  rename(canker = cankers) 
```

## Join coordinates

### Hernani

```{r}
hernani_coords1 <- st_read("/data/patrick/raw/survey_data/2016/hernani/hernani/arboles/arboles_hernani.shp") %>% 
  select(id) 
hernani_coords2 = as.data.frame(st_coordinates(hernani_coords1)) %>% 
  bind_cols(hernani_coords1) %>% 
  st_as_sf() %>% 
  st_set_geometry(NULL) %>% 
  rename_all(tolower)

data_tbl$hernani <- left_join(data_tbl$hernani, hernani_coords2,
  by = c("tree number" = "id")
)
```

### Laukiz 2

```{r}
laukiz2_coords <- st_read("/data/patrick/raw/survey_data/2016/laukiz2/arboles/Laukiz2_arboles_ETRS89.shp") %>% 
  st_set_geometry(NULL)

data_tbl$laukiz2 <- left_join(data_tbl$laukiz2, laukiz2_coords,
  by = c("tree number" = "id_arbol")
)
```

### Laukiz 1

```{r}
laukiz1_coords <- st_read("/data/patrick/raw/survey_data/2016/laukiz1/escaner/arboles_laukiz1_CT.shp") %>% 
  select(num)

laukiz1_coords2 = as.data.frame(st_coordinates(laukiz1_coords)) %>% 
  bind_cols(laukiz1_coords) %>% 
  st_as_sf() %>% 
  st_set_geometry(NULL) %>% 
  rename_all(tolower)

data_tbl$laukiz1 <- left_join(data_tbl$laukiz1, laukiz1_coords2,
  by = c("tree number" = "num")
)
```

### Luiando

```{r}
luiando_coords <- st_read("/data/patrick/raw/survey_data/2016/luiando/puntos_escaner/luiando_diam_CT_chapa.shp") %>% 
  select(id)

luiando_coords2 = as.data.frame(st_coordinates(luiando_coords)) %>% 
  bind_cols(luiando_coords) %>% 
  st_as_sf() %>% 
  st_set_geometry(NULL) %>% 
  rename_all(tolower)

data_tbl$luiando <- left_join(data_tbl$luiando, luiando_coords2,
  by = c("tree number" = "id")
)
```

### Oiartzun

```{r}
oiartzun_coords <- st_read("/data/patrick/raw/survey_data/2016/oiartzun/ARBOLES_antiguo/oiartzun_etrs89.shp") %>% 
  select(x, y, num) %>% 
  mutate(num = as.integer(as.character(num))) %>% 
  st_set_geometry(NULL)

data_tbl$oiartzun <- left_join(data_tbl$oiartzun, oiartzun_coords,
  by = c("tree number" = "num")
)
```

## Clean up

Ensure that no value > 100 exist.

```{r}
data_tbl %<>% 
  map(~ .x %>% 
        mutate(decoloration = if_else(decoloration > 100, 100, 
                                      as.numeric(decoloration))) %>% 
        mutate(defoliation = if_else(defoliation > 100, 100, 
                                      as.numeric(defoliation))))
```

NA means that there is no defoliation -> 0

```{r}
data_tbl %<>% 
  map(~ .x %>% 
        mutate(decoloration = if_else(is.na(decoloration), 0, 
                                      as.numeric(decoloration))) %>% 
        mutate(defoliation = if_else(is.na(defoliation), 0, 
                                     as.numeric(defoliation))) %>% 
        mutate(canker = if_else(is.na(canker), 0, 
                                as.numeric(canker))))
```

## st_as_sf() and save

```{r}
data_sf = map(data_tbl, ~ tidyr::drop_na(.x, c("x", "y")) %>% 
                st_as_sf(coords = c("x", "y"), crs = 32630))
# hernani is not needed
data_sf$hernani = NULL
```

```{r}
walk2(data_sf, seq_along(data_sf), 
      ~ st_write(.x, glue("/data/patrick/mod/tree-per-tree/2016/{name}/{name}.gpkg",
                          name = names(data_sf[.y])), delete_dsn = TRUE))
```
