---
title: "03-modeling"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Load packages

```{r, results='hide'}
library(mlr)
library(glue)
library(sf)
library(dplyr)
library(tibble)
library(purrr)
library(magrittr)
library(data.table)
```

# Read data

```{r}
data = map(c("laukiz1", "laukiz2", "luiando", "oiartzun"), ~ readRDS(glue("/data/patrick/mod/tree-per-tree/2016/{.x}/all-indices-{.x}.rda")))
```

# Extract coordinates

```{r}
coords = map(data, ~ as.data.frame(st_coordinates(.x)))
```

# Remove geometry 

```{r}
data %<>%
  map(~ st_set_geometry(.x, NULL)) 
```

# Remove columns with NA values

```{r}
test = as.data.table(data[[1]])
setDT(test)[test[, !Reduce(`|`, lapply(.SD, is.na))]]
```


```{r}
task = makeRegrTask(id = "laukiz1", data = data[[1]], 
                    target = "deftot", coordinates = coords[[1]],
                    )
```

```{r}
# predict.type for 'auc' (AUROC)
lrn <- makeLearner("regr.LiblineaRL2L2SVR")
getHyperPars(lrn)
getParamSet(lrn)
```


```{r}
ps <- makeParamSet(makeNumericParam("cost", lower = 0, upper = 100))
```

```{r}
ctrl <- makeTuneControlRandom(maxit = 50)
inner <- makeResampleDesc("SpCV", iters = 5)
```

```{r}
tune_wrapper <- makeTuneWrapper(lrn, resampling = inner, par.set = ps,
                               control = ctrl, show.info = TRUE,
                               measures = list(rmse))
```

```{r}
outer <- makeResampleDesc("SpRepCV", folds = 5, reps = 2)
```

```{r}
library(parallelMap)
parallelStart(mode = "multicore", level = "mlr.tuneParams", cpus = 48,
              mc.set.seed = TRUE) # only parallelize the tuning

set.seed(12345)
resa_brt_spatial <- mlr::resample(tune_wrapper, task,
                                  resampling = outer, extract = getTuneResult,
                                  show.info = TRUE, measures = list(rmse))

parallelStop()
```
