---
title: "03-modeling"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
---

# Load packages

```{r, results='hide'}
library(mlr)
library(mlrMBO)
library(glue)
library(sf)
library(dplyr)
library(tibble)
library(purrr)
library(magrittr)
library(data.table)
library(stringr)
library(ggpubr)
```

# Read data

```{r}
data = readRDS("/data/patrick/mod/hyperspectral/data_clean_with_indices/data_clean_standardized_bf2.rda")
coords = readRDS("/data/patrick/mod/hyperspectral/data_clean_with_indices/data_clean_standardized_bf2-coords.rda")
```

# Select plot

```{r}
data = data[[1]]
coords = coords[[1]]
```

Subset to indices shared by all plots.

```{r}
indices_shared = readRDS("/data/patrick/mod/hyperspectral/data_clean_with_indices/indices-shared-by-all-plots-bf2.rda")

data %<>% 
  dplyr::select(indices_shared)
```

# Create task

```{r}
task = makeRegrTask(id = "laukiz1", data = data, 
                    target = "defoliation", coordinates = coords)
```

# Modeling

## xgboost

```{r}
lrn_xgboost <- makeLearner("regr.xgboost",
                   par.vals = list(
                     objective = "reg:linear",
                     eval_metric = "error"
                   ))
```

```{r}
ps_xgboost <- makeParamSet(
  makeIntegerParam("nrounds", lower = 10, upper = 600),
  makeNumericParam("colsample_bytree", lower = 0.3, upper = 0.7),
  makeNumericParam("subsample", lower = 0.25, upper = 1),
  makeIntegerParam("max_depth", lower = 1, upper = 10),
  makeNumericParam("gamma", lower = 0, upper = 10),
  makeNumericParam("eta", lower = 0.001, upper = 0.6),
  makeNumericParam("min_child_weight", lower = 0, upper = 20)
)
```

```{r}
ctrl = makeMBOControl(propose.points = 1L)
ctrl = setMBOControlTermination(ctrl, iters = 20L)
ctrl = setMBOControlInfill(ctrl, crit = crit.ei)
tune.ctrl = makeTuneControlMBO(mbo.control = ctrl,
                               mbo.design = generateDesign(n = 30, 
                                                           par.set = ps_xgboost))
```

```{r}
inner <- makeResampleDesc("SpCV", iters = 5)
outer <- makeResampleDesc("SpRepCV", folds = 5, reps = 5)
```

### SpCV

```{r}
tune_wrapper <- makeTuneWrapper(lrn_xgboost, resampling = inner, par.set = ps_xgboost,
                                control = tune.ctrl, show.info = TRUE,
                                measures = list(rmse))
```

```{r}
library(parallelMap)
parallelStart(mode = "multicore", cpus = 25, level = "mlr.resample",
              mc.set.seed = TRUE) # only parallelize the tuning
set.seed(12345)
resa_rf <- mlr::resample(tune_wrapper, task,
                          resampling = outer, extract = getTuneResult,
                          show.info = TRUE, measures = list(rmse))

parallelStop()
saveRDS(resa_rf, "/data/patrick/mod/hyperspectral/spcv/laukiz1_xgboost.rda")
```
